name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to GitHub Pages
        run: |
          git branch -a  # List all branches to verify the existence of 'gh-pages'
          git checkout -b gh-pages  # Create and checkout 'gh-pages' branch if it doesn't exist
          git rm -r .            # Remove all existing files
          git checkout main -- index.html js/script.js css/main.css  # Copy the necessary files
          git add .
          git commit -m "Update HTML and CSS"
          git push origin gh-pages  # Push changes to 'gh-pages'
